### ISSUE TITLE
OpenCV error

### ISSUE THREAD

**Issue by pdxh0b0** [Digitelektro/MeteorDemod#98]
Windows 10![Screenshot (1366).png](https://github.com/Digitelektro/MeteorDemod/assets/93457948/bea37bea-4db5-4c38-b134-385b342ce647)

**Comment by pdxh0b0** [comment]
Occasionally,  
I am two passes in with mn2_3 today, no error

I post back after mn2_4 passes

 Was wondering if bad recorded data for satellite or if I needed to add something it couldn't find

**Comment by Digitelektro** [comment]
Please, if you have files that causes the error send it to me for test.  I need the cadu and tle files only.

**Comment by pdxh0b0** [comment]
Cadu's and tle
https://drive.google.com/file/d/1HOnmQgv9SSDgihjT1hLxqGo6hTlRv8tz/view?usp=drivesdk
![pdxh0b0_issue.png](https://github.com/Digitelektro/MeteorDemod/assets/93457948/8c06386c-c07b-475d-9790-745e9b53a2f0)

**Comment by Digitelektro** [comment]
Thank you! I know what is the problem, I will fix it soon.

**Comment by pdxh0b0** [comment]
Awesome, happened today decoding the third pass on Meteor-m2-3

**Comment by Digitelektro** [comment]
Now that M2-4 is back online, I continued to investigate the issue. I fixed a bug that can be related to this problem. I believe the problem was that meteordemod treated M2-4 as M2-3 when passes were available from both satellites and it tried to make a composite image. In such cases it could result in huge image generation which caused memory overflow and killed opencv.

The fix is available on the beta branch now, soon I will make a release. Can you please test it?

**Comment by pdxh0b0** [comment]
> Now that M2-4 is back online, I continued to investigate the issue. I fixed a bug that can be related to this problem. I believe the problem was that meteordemod treated M2-4 as M2-3 when passes were available from both satellites and it tried to make a composite image. In such cases it could result in huge image generation which caused memory overflow and killed opencv.
> 
> The fix is available on the beta branch now, soon I will make a release. Can you please test it?

Well download and use with m23 & m24 today, ty

**Comment by Digitelektro** [comment]
Meteordemod 2.6.5 is released with the fix. Please give a feedback once you've tested it, so I can close the issue. Thanks!

**Comment by pdxh0b0** [comment]
> Meteordemod 2.6.5 is released with the fix. Please give a feedback once you've tested it, so I can close the issue. Thanks!
(Edit.updated the tle..I ran m23 and m24 a second time each, m24 made the two pass composite,  m23 still errors on the third pass composite)

Still getting an opencv error
![Screenshot (1432).png](https://github.com/Digitelektro/MeteorDemod/assets/93457948/dd588725-f50d-47dc-aa05-a6e0d18220e4)

Included in zip 3 cadu's from yesterday's M23, 2 cadu's from yesterday's M24, tle.txt, error txt from image

https://drive.google.com/file/d/1ZTVdt9IvxJ3SRS_cBM8YS0NnZZbKgTaQ/view?usp=drivesdk
